### ISSUE TITLE
Show sigops for template

### ISSUE THREAD

**Issue by Sjors** [0xB10C/miningpool-observer#61]
This should be a matter of summing the `sigops` field for each transaction in the template.

**Comment by 0xB10C** [comment]
Implementing this in #63. Might also want to add this for blocks and individual transactions. That means manually counting sigops though.

**Comment by 0xB10C** [comment]
Adding sigops counting in https://github.com/0xB10C/rawtx-rs/pull/12 for making these stats available for blocks and transactions too.
