### ISSUE TITLE
Missing Transactions section takes too much time to load

### ISSUE THREAD

**Issue by dev7ba** [0xB10C/miningpool-observer#69]
I've been serching for txId a832c2fe8c8bda177eb26dbd032879e208074780bb485dbe96104922d8c5f5f6 (as it has been missing from templates 96 times in my mempoolexplorer.com node) in your web, and I've realized that it takes a lot of time to load the missing transactions section.

Not sure why, other times I've visited the page, it has been much faster. 

https://miningpool.observer/missing

**Comment by 0xB10C** [comment]
It seems to me that I didn't have this transaction in any of my templates: https://miningpool.observer/missing/a832c2fe8c8bda177eb26dbd032879e208074780bb485dbe96104922d8c5f5f6

I'll look into the slow load times. The database query can probably be improved.
